# client/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# Copy all files
COPY . .

# Expose the port React uses
EXPOSE 5000

# Start the app in dev mode
CMD ["npm", "run", "dev"]
